version: "3.3"

services:
  postgres:
    image: postgres
#    volumes:
#      - ./data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_NAME=mind_palace
      - POSTGRES_USER=mind_palace
      - POSTGRES_PASSWORD=1Qetuwry


  mind_palace:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    environment:
      - POSTGRES_NAME=mind_palace
      - POSTGRES_USER=mind_palace
      - POSTGRES_PASSWORD=1Qetuwry
    depends_on:
      - postgres